on:
  push:
    branches:
      - main
      - v6.[1-9]
      - v7.[1-9]
      - 'feature-**'
    paths:
      - 'agent/**'
      - 'message/**'
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true
        type: string

name: build agent

env:
  IMAGE: "deepflow-agent"

jobs:
  build_agent:
    name: build agent
    runs-on: "cirun-aws-amd64-32c--${{ github.run_id }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # - name: install docker
      #   run: |
      #     sudo systemctl stop unattended-upgrades
      #     curl -fsSL https://get.docker.com | bash

      - name: docker version
        run: |
          docker version
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build  deepflow agent
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: agent/docker/dockerfile-build
          platforms: linux/amd64
          outputs: type=local,dest=./agent/output/
          build-args: |
            GITHUB_REF_NAME=${{ github.ref_name }}

      - name: Check dynamic dependencies
        run: |
          required_libs=()
          in_arm_section=false
          while IFS= read -r line; do
              if [[ "$line" =~ ^\#\ X86\ Dynamic\ Libraries ]]; then
                  in_arm_section=true
                  continue
              fi

              if [[ "$line" =~ ^\#\  ]] && [[ "$in_arm_section" = true ]]; then
                  break
              fi

              if [[ "$in_arm_section" = true ]] && [[ "$line" =~ \*\*([^\*]+)\*\* ]]; then
                  required_libs+=("${BASH_REMATCH[1]}")
              fi
          done < agent/README.md
          dynamic_libs=$(ldd agent/output/target/release/deepflow-agent | awk '{print $1}' | xargs -n1 basename)
          echo "All dynamic dependency: ${dynamic_libs}"
          for lib in $dynamic_libs; do
              if [[ ! " ${required_libs[@]} " =~ " ${lib} " ]]; then
                  echo "Warning: Do not introduce any additional dynamic library dependencies!: ${lib}"
                  exit 1
              fi
          done

      - name: Package code build results
        run: |
          tar cvf agent-artifact-amd64.tar agent/output/target/release/deepflow-agent agent/output/target/release/deepflow-agent-ctl agent/output/src/ebpf/deepflow-ebpfctl
          curl -o agent/output/target/release/ecapture https://deepflow-ce.oss-cn-beijing.aliyuncs.com/pkg/compile/x86_64/ecapture
          chmod a+x agent/output/target/release/ecapture

      - name: Archive code build results
        uses: actions/upload-artifact@v4
        with:
          name: agent build results amd64
          path: |
            agent-artifact-amd64.tar

  build_agent_arm64:
    name: build agent arm64
    runs-on: "cirun-aws-arm64-32c--${{ github.run_id }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # - name: install docker
      #   run: |
      #     sudo systemctl stop unattended-upgrades
      #     curl -fsSL https://get.docker.com | bash

      - name: docker version
        run: |
          docker version
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build  deepflow agent
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: agent/docker/dockerfile-build-aarch64
          platforms: linux/arm64
          outputs: type=local,dest=./agent/output/
          build-args: |
            GITHUB_REF_NAME=${{ github.ref_name }}

      - name: Check dynamic dependencies
        run: |
          required_libs=()
          in_arm_section=false
          while IFS= read -r line; do
              if [[ "$line" =~ ^\#\ ARM\ Dynamic\ Libraries ]]; then
                  in_arm_section=true
                  continue
              fi

              if [[ "$line" =~ ^\#\  ]] && [[ "$in_arm_section" = true ]]; then
                  break
              fi

              if [[ "$in_arm_section" = true ]] && [[ "$line" =~ \*\*([^\*]+)\*\* ]]; then
                  required_libs+=("${BASH_REMATCH[1]}")
              fi
          done < agent/README.md
          dynamic_libs=$(ldd agent/output/target/release/deepflow-agent | awk '{print $1}' | xargs -n1 basename)
          echo "All dynamic dependency: ${dynamic_libs}"
          for lib in $dynamic_libs; do
              if [[ ! " ${required_libs[@]} " =~ " ${lib} " ]]; then
                  echo "Warning: Do not introduce any additional dynamic library dependencies!: ${lib}"
                  exit 1
              fi
          done

      - name: Package code build results
        run: |
          tar cvf agent-artifact-arm64.tar agent/output/target/release/deepflow-agent agent/output/target/release/deepflow-agent-ctl agent/output/src/ebpf/deepflow-ebpfctl
          curl -o agent/output/target/release/ecapture https://deepflow-ce.oss-cn-beijing.aliyuncs.com/pkg/compile/aarch64/ecapture
          chmod a+x agent/output/target/release/ecapture

      - name: Archive code build results
        uses: actions/upload-artifact@v4
        with:
          name: agent build results arm64
          path: |
            agent-artifact-arm64.tar

  build_agent_image:
    name: build agent image
    needs:
    - build_agent
    - build_agent_arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # - name: install docker
      #   run: |
      #     sudo systemctl stop unattended-upgrades
      #     curl -fsSL https://get.docker.com | bash

      - name: docker version
        run: |
          docker version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download code build results
        uses: actions/download-artifact@v4
        with:
          name: agent build results arm64
          path: .

      - name: Download code build results
        uses: actions/download-artifact@v4
        with:
          name: agent build results amd64
          path: .

      - name: Unpack code build results
        run: |
          mkdir -p x86_64
          mkdir -p aarch64
          tar xvf agent-artifact-amd64.tar -C x86_64
          tar xvf agent-artifact-arm64.tar -C aarch64
          curl -o x86_64/agent/output/target/release/ecapture https://deepflow-ce.oss-cn-beijing.aliyuncs.com/pkg/compile/x86_64/ecapture
          chmod a+x x86_64/agent/output/target/release/ecapture
          curl -o aarch64/agent/output/target/release/ecapture https://deepflow-ce.oss-cn-beijing.aliyuncs.com/pkg/compile/aarch64/ecapture
          chmod a+x aarch64/agent/output/target/release/ecapture

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GHCR_PUSH_TOKEN }}"

      - name: set env
        run: |
          echo "IMAGE_TAG_PREFIX=${{ github.ref_name }}"|sed 's|=main$|=latest|' >> $GITHUB_ENV
          echo "IMAGE_TAG=$(git rev-list --count HEAD)" >> $GITHUB_ENV
      - name: qemu workaround
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
      - name: Build and push deepflow agent images to ghcr
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: agent/docker/dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            "ghcr.io/${{ github.repository_owner }}/deepflow-ce/${{ env.IMAGE }}:${{ env.IMAGE_TAG_PREFIX }}-${{ env.IMAGE_TAG }}"
            "ghcr.io/${{ github.repository_owner }}/deepflow-ce/${{ env.IMAGE }}:${{ env.IMAGE_TAG_PREFIX }}"

  build_agent_static_link:
    name: build agent static link
    runs-on: "cirun-aws-amd64-32c--${{ github.run_id }}"
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: docker version
        run: |
          docker version
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build deepflow agent
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: agent/docker/dockerfile-build-static-link
          platforms: linux/amd64
          outputs: type=local,dest=./agent/output/
          build-args: |
            GITHUB_REF_NAME=${{ github.ref_name }}

  build_agent_arm64_static_link:
    name: build agent arm64 static link
    runs-on: "cirun-aws-arm64-32c--${{ github.run_id }}"
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: docker version
        run: |
          docker version
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build deepflow agent
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: agent/docker/dockerfile-build-aarch64-static-link
          platforms: linux/arm64
          outputs: type=local,dest=./agent/output/
          build-args: |
            GITHUB_REF_NAME=${{ github.ref_name }}
